#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo_map="$repo_root/.codex/skills/ai-portfolio-repo-context/references/repo-map.md"
tmp_map="$(mktemp)"
trap 'rm -f "$tmp_map"' EXIT

{
  printf '# Repo Map\n\n'
  printf 'Generated by `./scripts/update_skill_references.sh`.\n\n'
  printf '## Top-level structure\n\n'
  printf '```text\n'
  find "$repo_root" \
    -path "$repo_root/.git" -prune -o \
    -path "$repo_root/.venv" -prune -o \
    -path "$repo_root/.pytest_cache" -prune -o \
    -path "$repo_root/src/ai_portfolio.egg-info" -prune -o \
    -name .DS_Store -prune -o \
    -name __pycache__ -prune -o \
    -print | sed "s|$repo_root|.|" | sort
  printf '```\n\n'
  printf '## Key portfolio folders\n\n'
  printf -- '- `src/ai_portfolio/`: runnable portfolio examples\n'
  printf -- '- `notebooks/`: notebook companions and walkthrough placeholders\n'
  printf -- '- `docs/`: GitHub Pages portfolio site\n'
  printf -- '- `.codex/skills/`: repo-local Codex skills\n'
  printf -- '- `scripts/update_skill_references.sh`: refreshes this file\n'
} > "$tmp_map"

chmod 644 "$tmp_map"
mv -f "$tmp_map" "$repo_map"
trap - EXIT

printf 'Updated %s\n' "$repo_map"
